### ISSUE TITLE
× Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.  note: This error originates from a subprocess, and is likely not a problem with pip.

### ISSUE THREAD

**Issue by sherazi5110** [apeatling/ollama-voice-mac#19]
Collecting openai-whisper@ git+https://github.com/openai/whisper.git@ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab (from -r /Users/syedalihamza/Downloads/requirements.txt (line 13))
  Cloning https://github.com/openai/whisper.git (to revision ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab) to /private/var/folders/r8/y63fgg1x6y3gj4yw7pzwt3nw0000gn/T/pip-install-20zcttou/openai-whisper_eb645e5a0d664d8b9947920f546495d5
  Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git /private/var/folders/r8/y63fgg1x6y3gj4yw7pzwt3nw0000gn/T/pip-install-20zcttou/openai-whisper_eb645e5a0d664d8b9947920f546495d5
  Running command git rev-parse -q --verify 'sha^ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab'
  Running command git fetch -q https://github.com/openai/whisper.git ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab
  Running command git checkout -q ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab
  Resolved https://github.com/openai/whisper.git to commit ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      <string>:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/r8/y63fgg1x6y3gj4yw7pzwt3nw0000gn/T/pip-build-env-dhlb3jw_/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/r8/y63fgg1x6y3gj4yw7pzwt3nw0000gn/T/pip-build-env-dhlb3jw_/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/r8/y63fgg1x6y3gj4yw7pzwt3nw0000gn/T/pip-build-env-dhlb3jw_/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 516, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/r8/y63fgg1x6y3gj4yw7pzwt3nw0000gn/T/pip-build-env-dhlb3jw_/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 21, in <module>
        File "<string>", line 11, in read_version
      KeyError: '__version__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by manenga** [comment]
Same here

**Comment by bml3i** [comment]
Exactly the same issue when trying to install whisper...
